<?php

/**
 * Implements hook_user_login().
 *
 * Override the default redirect, /user/UID, to go to the front page instead.
 */
function shapermit_forms_user_login(&$edit, $account) {
//  if ($account->uid != 1) {
    $edit['redirect'] = 'node/645';
//  }
}

function shapermit_forms_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    $form['field_i_am']['#weight'] = "20";
  }

  if($form_id == 'user_profile_form') {
    $form['#submit'][] = 'shapermit_forms_profile_form_submit';
  }
}

function shapermit_forms_profile_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'node/645';
}
