<?php

/**
 * Implements hook_user_login().
 *
 * Override the default redirect, /user/UID, to go to the front page instead.
 */
function shapermit_forms_user_login(&$edit, $account) {

    $edit['redirect'] = 'node/645';

}


/**
 * Implements hook_form_alter().
 *
 * Rearranges weighting of fields.
 */
function shapermit_forms_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    $form['field_i_am']['#weight'] = "20";
  }
}
