<?php



/**
 * Implements hook_block_info().
 */
function fial_home_block_info() {
  $blocks = array();
  $blocks['fial_home'] = array(
    'info' => t('Fial home block'),
  );   
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function fial_home_block_view($delta='') {
  $block = array();
  global $base_url, $user;
  
     
  switch($delta) {
        case 'fial_home':
            $div1 = '<div class=span4>'.views_embed_view('homepage_news_blocks','news').'</div>';
            $div2 = '<div class=span4>'.views_embed_view('homepage_news_blocks','attachment_1').'</div>';
            $div3 = '<div class=span4>'.views_embed_view('homepage_news_blocks','attachment_2').'</div>';         
            $content = sprintf('<div class=span12>%s%s%s </div>', $div1, $div2, $div3);  
            $block['content'] = $content;            
        break;
       
  }
  return $block;
}


